In [1]:
# 1. Create a vector with values ranging from 10 to 49.


In [2]:
import numpy as np
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8.

In [4]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 3. Create a 10x10 array with random values and find the minimum and maximum values.


In [6]:
arr=np.random.rand(100).reshape(10,10)
print(arr)
print("Min value:",np.min(arr))
print("Max value:",np.max(arr))

[[0.86786473 0.83308987 0.51456702 0.45004839 0.24703216 0.85310726
  0.53177738 0.17265511 0.77376007 0.60544938]
 [0.92086277 0.35591146 0.72452176 0.04295035 0.83051146 0.31385861
  0.12930498 0.237248   0.76452038 0.78305965]
 [0.72321301 0.23977016 0.6646701  0.67226335 0.55202787 0.1017392
  0.45494569 0.12516401 0.4955668  0.14625821]
 [0.22858644 0.73519394 0.83829697 0.28243555 0.64117708 0.25611319
  0.76600307 0.23492228 0.13270948 0.55924201]
 [0.01193963 0.93348875 0.59597355 0.27664572 0.96167426 0.12951636
  0.35349985 0.95156404 0.22446937 0.88249366]
 [0.68105543 0.15536819 0.57131887 0.90883503 0.66018773 0.30197499
  0.52537655 0.03398792 0.08242644 0.25391815]
 [0.45316667 0.95124087 0.02216468 0.7235994  0.3948648  0.46775992
  0.44506339 0.47475876 0.44480672 0.92100395]
 [0.90998499 0.53497231 0.27358963 0.20938838 0.04194798 0.10881348
  0.58604596 0.64276361 0.78877573 0.74647118]
 [0.54879775 0.63975371 0.0115517  0.307932   0.79721618 0.05996375
  0.94969087 

In [7]:
# 4. Create a random vector of size 30 and find the mean value.


In [8]:
arr=np.arange(1,31)
print(arr)
print()
print("Mean :",np.mean(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

Mean : 15.5


In [9]:
#5. Perform addition, subtraction, multiplication, and division of two given NumPy arrays.

In [10]:
var1=np.array([5,6,7,8])
var2=np.array([1,2,3,4])
print(var1)
print()
print(var2)
print()
varadd=np.add(var1,var2)
varsub=np.subtract(var1,var2)
varmul=np.multiply(var1,var2)
vardiv=np.divide(var1,var2)
print("Addition:",varadd)
print("Subtraction:",varsub)
print("Multiplication:",varmul)
print("Division:",vardiv)

[5 6 7 8]

[1 2 3 4]

Addition: [ 6  8 10 12]
Subtraction: [4 4 4 4]
Multiplication: [ 5 12 21 32]
Division: [5.         3.         2.33333333 2.        ]


In [11]:
#6. Calculate the element-wise square root of a given NumPy array.

In [12]:
var1=np.array([5,6,7,8])
print(np.sqrt(var1))


[2.23606798 2.44948974 2.64575131 2.82842712]


In [13]:
#7. Stack two given arrays vertically and horizontally.

In [22]:
ar1 = np.array([9, 8, 3])
ar2 = np.array([2, 5, 6])
ar_v = np.vstack((ar1, ar2))
ar_h = np.hstack((ar1, ar2))
print("Vertically:\n",ar_v)
print("Horizontaly:\n",ar_h)

Vertically:
 [[9 8 3]
 [2 5 6]]
Horizontaly:
 [9 8 3 2 5 6]


In [15]:
#8. Reshape a given 1D array into a 2D array with 3 rows and 4 columns.

In [16]:
var1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#9. Transpose a given 2D array and then flatten it into a 1D array.

In [18]:
var1=np.array([[1,2,3],[4,5,6]])
print(" Transpose_Array:\n", np.transpose(var1))
print()
print("Flatten_array:",var1.flatten())


 Transpose_Array:
 [[1 4]
 [2 5]
 [3 6]]

Flatten_array: [1 2 3 4 5 6]


In [19]:
#10. Create a random of array and implement different slicing methods on it

In [20]:
var=np.array([1,2,3,4,5,6,7])
print(var)
print()
print("values 2 to 5:",var[1:5])
print("values 2 to End:",var[1:])
print("values Start to 5:",var[:5])
print("Reverse:",var[::-1])
print("Stop:",var[::2])
print("Complete array:",var[:])

[1 2 3 4 5 6 7]

values 2 to 5: [2 3 4 5]
values 2 to End: [2 3 4 5 6 7]
values Start to 5: [1 2 3 4 5]
Reverse: [7 6 5 4 3 2 1]
Stop: [1 3 5 7]
Complete array: [1 2 3 4 5 6 7]
